package com.sensorweb.sosobsservice.dao;

import com.sensorweb.sosobsservice.entity.dataStatistics;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;

@Repository
@Mapper
public interface dataStatisticsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_item_statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_item_statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    int insert(dataStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_item_statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    dataStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_item_statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    List<dataStatistics> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_item_statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    int updateByPrimaryKey(dataStatistics record);



    int getHBAirNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getHBAirNum();


    int getCHAirNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getCHAirNum();


    int getTWAirNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getTWAirNum();

    int getSuperAirNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getSuperAirNum();


    int getWaterNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getWaterNum();


    int getWaterQualityNum();

    int getWaterPollutionNum();

    int getWaterQualityAutoNum();

    int getGFNum();




    int getWeatherNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getWeatherNum();


    int getCHWeatherNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getCHWeatherNum();



    int getHBWeatherNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getHBWeatherNum();



    int getModisNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getModisNum();



    int getGPMNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getGPMNum();

    int getGLDASNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getGLDASNum();


    int  getLandsatNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int  getLandsatNum();

    int getHimawariNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getHimawariNum();



    int getMailDataNum();

    int getUAVNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getUAVNum();


    int getFYNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getFYNum();


    int getTXZNumByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getTXZNum();



    int getProductNumByTime(@Param("type") String type,@Param("begin") Instant begin, @Param("end") Instant end);

    int getProductNumByTime2(@Param("type") String type,@Param("end") Instant end);

    int getProductTypeNum(@Param("type") String type);

    int getProductNum(@Param("type") String type);

    int getInterfaceNum(@Param("type") String type);

    List<String> getFilepath(@Param("type") String type, @Param("database") String database);

    List<String> getFilepath2(@Param("database") String database);

    long getDatabaseSize(@Param("table") String table);


    int getwaterAutoNum();

    int getyaEBNum();

    int getyaMRNum();

    int getSentinelNum();

    int getCopernicusNum();

    int getSentineByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getCopernicus(@Param("begin") Instant begin, @Param("end") Instant end);

    int getLittleSensorNumber();

    int getNumberByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getWeatherSensorNumber();

    int getWeatherSensorByTime(@Param("begin") Instant begin, @Param("end") Instant end);

    int getTodayNumber(@Param("time")Instant time);
}