package com.sensorweb.sosobsservice.entity;

import lombok.Data;

import java.time.Instant;
import java.util.Date;

@Data
public class dataStatistics {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_item_statistics.id
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_item_statistics.job_id
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    private String jobId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_item_statistics.statistics
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    private String statistics;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column data_item_statistics.create_time
     *
     * @mbggenerated Fri Sep 16 15:56:33 CST 2022
     */
    private Instant createTime;
}